# MIT License

# Copyright (c) 2023 Replicable-MARL

# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

# MAPPO parameters

# Detailed explanation for each hyper parameter can be found in ray/rllib/agents/ppo/ippo.py

algo_args:
  # GAE
  use_gae: True
  lambda: 0.95
  # Entrenamiento
  lr: 0.0001
  gamma: 0.98
  num_sgd_iter: 5  # 10
  batch_mode: 'complete_episodes'
  batch_episode: 10
  # PPO clip
  clip_param: 0.15  # 0.2
  kl_coeff: 0.1  # 0.2
  kl_target: 0.02
  # Crítico
  vf_clip_param: 20.0  # 50.
  vf_loss_coeff: 0.1  # valor menor a 1 le da más importancia al actor (política)->el crítico es el que tiene más peso en el loss total
  # Gradientes
  grad_clip: 0.5
  # Exploración
  entropy_coeff: 0.01
  # PDN
#  kl_coeff: 0.2
#  num_sgd_iter: 5
#  vf_loss_coeff: 0.5
#  entropy_coeff: 0.01
#  vf_clip_param: 10.0
#  batch_mode: "truncate_episodes"
  # PGW
#  gae_lambda: 0.95 # probar 0.9



